### ISSUE TITLE
Use Best Practices for Firebase configuration: Move hardcoded API keys to .env

### ISSUE THREAD

**Issue by steveWDamesJr** [voscarmv/issue-finder#10]
### Location 
 - src/utility/firebase.js
 

### Instructions 
- Create .env file (if not already created)
- Move to .env file:
    - apikey
    - authDomain
    - projectId
    - storageBucket
    - messageingSenderId
    - appId
    - measurementId
  
- Open a new pull request with changes

Do not hesitate to let us know if you have any questions 👋

**Comment by 0xPranjl** [comment]
can you assign it to me??

**Comment by 0xPranjl** [comment]
done opened a PR
