### ISSUE TITLE
Add more detail to results cards

### ISSUE THREAD

**Issue by steveWDamesJr** [voscarmv/issue-finder#11]
### Snapshot

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/81635839/193433434-d394dcf0-deb0-4498-b2a1-8ba605807efd.png">

### Suggestions

- We would like to include titles to our cards. This could improve the UX of the app.

 - Open a new pull request with changes

Do not hesitate to let us know if you have any questions 👋

**Comment by aadilkhalifa** [comment]
Hi. Can I work on this?

**Comment by shadmanhere** [comment]
Hi @aadilkhalifa, go ahead, make the changes and create a pull request. We would love to have you as a contributor.

**Comment by aadilkhalifa** [comment]
Hi. 

I've created a PR for the issue. Open to feedback.
[Link to PR](https://github.com/voscarmv/issue-finder/pull/22)
