### ISSUE TITLE
Feat: Create a light/dark toggle theme

### ISSUE THREAD

**Issue by steveWDamesJr** [voscarmv/issue-finder#12]
## Toggle Light/Dark mode

- Currently Issue Finder has dark theme. It would be great to improve accessibility to add a Light theme feature to the app.
- Open a new pull request with changes

Do not hesitate to let us know if you have any questions 👋

**Comment by Maaz4324** [comment]
Hey, I did this one

**Comment by Maaz4324** [comment]
Please check I think I have pulled request. I'm pretty new, don't know if you got the updated code

**Comment by deyemiobaa** [comment]
Hi, @Maaz4324. Your pull request is not on this repo. Follow this [guide](https://github.com/deyemiobaa/issue-finder/blob/update-contributing-guide/CONTRIBUTING.md#getting-started) to get started and create your first PR
