### ISSUE TITLE
Make filter stay at top of the screen

### ISSUE THREAD

**Issue by steveWDamesJr** [voscarmv/issue-finder#13]
### Filter
<img width="580" alt="image" src="https://user-images.githubusercontent.com/81635839/193433694-32f4d700-0a15-4319-90c3-f2f2db1c80ab.png">

### Mobile View
<img width="500" alt="image" src="https://user-images.githubusercontent.com/81635839/193433753-2b7b05c6-f58c-42f2-9652-c5d7ee1641ab.png">

### Desktop View
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/81635839/193433641-fca714da-0644-4a74-b91a-c7f5b24f82ac.png">

- We are looking to improve the UX of the app by always being able to access the filter inputs even if there is a large output list.
- We should be able to scroll through output issues without loosing sight of our filter options. 

- Open a new pull request with changes.

Do not hesitate to let us know if you have any questions 👋

**Comment by RahulSankhla312** [comment]
hey @steveWDamesJr can you assign this issue to me.

**Comment by shivam-Purohit** [comment]
Can you explain this more, I can work on this if you like.

**Comment by shadmanhere** [comment]
Hi @shivam-Purohit, We want that the Filter section sticks on top of the screen when we scroll down the web page.

## Filter
<img width="580" alt="image" src="https://user-images.githubusercontent.com/81635839/193433694-32f4d700-0a15-4319-90c3-f2f2db1c80ab.png">

**Comment by shivam-Purohit** [comment]
I can work on this issue , I have fair knowledge of web development and react. Keeping position as absolute might solve the problem. Shall I try a solution and send a PR . You can suggest any changes if required.

**Comment by shadmanhere** [comment]
@shivam-Purohit, yeah sure go ahead.
