### ISSUE TITLE
Fix h1 Title sizing issue

### ISSUE THREAD

**Issue by steveWDamesJr** [voscarmv/issue-finder#14]
### h1 Tittle 
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/81635839/193433845-ce23b632-abfe-4ad1-8af1-9be81e99ac06.png">

### h1 properties being blocked (size of "Title" is small)
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/81635839/193433855-aea1739f-9e46-4a42-9c5d-7525769f16c0.png">

### Ideal size of "Issues" Tittle
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/81635839/193433894-5dc27a0a-4530-44a3-999f-7940c4992213.png">

- We would like to have the "Issues Title appear with proper h1 sized formatting as shown above in the "Ideal Size" snapshot.
- Open a new pull request with changes

Do not hesitate to let us know if you have any questions 👋

**Comment by Sayak-singha** [comment]
I want to work on this issue

**Comment by shadmanhere** [comment]
Hi @Sayak-singha, go ahead, make the changes and create a pull request. We would love to have you as a contributor.

**Comment by VidishaAG** [comment]
Can I be assigned please?

**Comment by shadmanhere** [comment]
Hi @VidishaAG, 
yes, go ahead and make your contribution. We are open to contributions from everybody.

**Comment by Arpit-mohankar** [comment]
i would like to work on this issue
