### ISSUE TITLE
Update README to make the Dependencies instructions clearer

### ISSUE THREAD

**Issue by Benmuiruri** [voscarmv/issue-finder#19]
Hi Team,

Great work on creating this amazing tool. I was setting up the project on my machine and I don't think it might be easily understandable to beginners that they need to add a GitHub token to the `label_grouping.js `file. 

I suggest improving the wording in the dependencies section in the readme file to make it more explicit about what one needs to do. 

Also, the linters section mentions creating a `.eslintrc.json` file, but the file already exists. I can also fix that issue since it is updating the Readme. 

I would be happy to make the improvement.

**Comment by shadmanhere** [comment]
Hi @Benmuiruri, 
We are open to contributions. So you can make changes and open a pull request.
We would really like to have you as a contributor to our project.

**Comment by Benmuiruri** [comment]
Hi @shadmanhere thanks. I'll make the contribution and open a PR

**Comment by Benmuiruri** [comment]
Hi, @shadmanhere I would like to clarify something. 

As part of the setup, should the user create a `.env` file in the root folder, then copy what is in the `.env.sample` and copy that into the `.env `file? Then replace the `REACT_APP_API_KEY` with their GitHub token ? 

Do I have that correct? 

Second, the `label_grouping.js` file has the following code...  `let private_tkn = 'ENTER A VALID TOKEN';` should a user also add the same GitHub token there?

**Comment by deyemiobaa** [comment]
Hey @Benmuiruri. I contributed to this project recently. 
For the setup, 
- create a `.env` file in the root
- Generate a GitHub token
- paste this `REACT_APP_API_KEY=ghp_my_token` in the `.env` file

For `label_groupings.js`, that file isn't used anywhere in production yet. Nothing is being exported for use elsewhere. so you can ignore that.

**Comment by Benmuiruri** [comment]
Thanks @deyemiobaa, I will update the readme accordingly. 

Just to clarify, should a user copy what is in the .env.sample and copy that into the created .env file? Then replace the REACT_APP_API_KEY with their GitHub token ?

**Comment by deyemiobaa** [comment]
Hey @Benmuiruri. I already opened a PR to handle this. You can view it [here](https://github.com/voscarmv/issue-finder/pull/23)

**Comment by Benmuiruri** [comment]
haha, nice work. Two of the issues I was planning to do as part of hactoberfest ...have now just been done :sweat_smile: 

I had actually updated the readme, I was just waiting for the clarification before opening the PR. 

I guess I should find other issues

**Comment by deyemiobaa** [comment]
😬 Sorry man. I'm sure you'll find something.

There's a feature I was thinking of perhaps you can work on it. Custom filter for the issues that have been generated. Users can filter by date or last commit (if that's available in the fetched data)

**Comment by Benmuiruri** [comment]
That's a good idea. I will check it out

**Comment by shadmanhere** [comment]
Hi @Benmuiruri,
@deyemiobaa has made changes to CONTRIBUTING.md. You can still make changes to Readme, if you like.

**Comment by Benmuiruri** [comment]
Ohh, alright. let me do that.

**Comment by steveWDamesJr** [comment]
> 😬 Sorry man. I'm sure you'll find something.
> 
> There's a feature I was thinking of perhaps you can work on it. Custom filter for the issues that have been generated. Users can filter by date or last commit (if that's available in the fetched data)

Hello @deyemiobaa 👋 . Thank you for stellar contribution to our open source app. That is an amazing idea. Please do open an issue detailing what you've said here. 

Cheers and Happy Coding!
