### ISSUE TITLE
In firefox for windows, spacing above and below the progress bar is not working as it is working in chrome

### ISSUE THREAD

**Issue by shadmanhere** [voscarmv/issue-finder#2]
In firefox for windows, spacing above and below the progress bar is not working, as it is working in chrome.
![Screenshot 2022-08-20 at 20-47-52 React App](https://user-images.githubusercontent.com/17983225/185754223-fd42fe35-1261-4a65-bdfd-d35fe4159884.png)

**Comment by rcqx** [comment]
There are some hard-coded br tags there. We can update that and rely on CSS instead there I guess

**Comment by steveWDamesJr** [comment]
Awesome find @shadmanhere!

Please find multi-browser support of **Progress Bar** spacing 👇 

<img width="1440" alt="Screen Shot 2022-08-20 at 12 21 28 PM" src="https://user-images.githubusercontent.com/81635839/185759153-10ee3c40-7119-451f-9cb2-7747d61220c1.png">

**Comment by steveWDamesJr** [comment]
> There are some hard-coded br tags there. We can update that and rely on CSS instead there I guess

Good call @jr-cast. Please check my latest commit to verify resolution of this issue, thanks!

**Comment by shadmanhere** [comment]
Thanks, @jr-cast and @steveWDamesJr issue is now resolved.
