### ISSUE TITLE
Update import path for App.js to fix failing tests 

### ISSUE THREAD

**Issue by Benmuiruri** [voscarmv/issue-finder#20]
The tests are currently not passing due to an incorrect path importing `App.js ` in App.test.js. 

Attached is a screenshot showing the error
![Screenshot from 2022-10-03 17-25-59](https://user-images.githubusercontent.com/2597305/193602921-86e61793-bcbd-46b8-a9f6-4070b0d60cf5.png)

I would like to work on this issue and fix that.

**Comment by shadmanhere** [comment]
Hi @Benmuiruri, 
We are open to contributions. So you can make changes and open a pull request.
We would really like to have you as a contributor to our project.

**Comment by Benmuiruri** [comment]
Hi @shadmanhere thanks. I'll make the contribution and open a PR

**Comment by Croustys** [comment]
Oh I'm sorry didn't see your reply that you'll work on the issue!
