### ISSUE TITLE
Filter Issues as either assigned or unassigned

### ISSUE THREAD

**Issue by Benmuiruri** [voscarmv/issue-finder#25]
Hi Team, 

Currently, the list of issues displays all issues (Both assigned and unassigned together)

I would like to suggest. Allowing the user to filter the issues found either by all, assigned, or unassigned.

I have given it a try, but I have not been able to get it to work. I still haven't found the right approach. 

I will continue trying but if someone else can manage to get it to work. Please post a comment on this issue.

**Comment by steveWDamesJr** [comment]
Hello @Benmuiruri,

Thank you for the recent great contributions you have made to Issue FInder 🙌 . 

Your approach, if you develop a solution, is welcomed. If not, we thank you for raising this issue!

**Comment by shadmanhere** [comment]
fixed in #36
