### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by radhika141** [voscarmv/issue-finder#34]
**Is your feature request related to a problem? Please describe.**
To claim copyright issues, I want to add footer to the site

**Describe the solution you'd like**
Add footer to the site, to claim copyright issues

**Describe alternatives you've considered**

**Additional context**

**Comment by shadmanhere** [comment]
Hi @radhika141, thanks for opening an issue. It's great to have you here. I don't know if we want a footer on our site or not. I will talk about this with my team and inform you. Whether to go forward with this or not.
