### ISSUE TITLE
App seems to crash when selecting `All` labels for `Rails`

### ISSUE THREAD

**Issue by ricardovaltierra** [voscarmv/issue-finder#38]
Opening the App and setting `All` labels for `Rails` framework causes currently a blank page and the following log messages: `TypeError: u is null` and `Uncaught TypeError: u is null`

![image](https://user-images.githubusercontent.com/52725285/204129168-936da239-2c94-4650-8ebe-bd108b55cffb.png)

 - OS: `Ubuntu 20.04`
 - Browser: Firefox
 - Version: 107.0 (64-bit)

**Comment by shadmanhere** [comment]
Great find @ricardovaltierra 👍 . We are looking into it and will resolve it as soon as possible.

**Comment by ricardovaltierra** [comment]
That's  really good  to know! Great to see was solved so soon 👍🏾
